In [ ]:
import skimage
import numpy as np
from skimage import img_as_ubyte
import cv2

In [ ]:
import cv2
def cropping_helper(image_path, target_size):
    # Load the image and convert it to grayscale
    image = cv2.imread(image_path)
    gray= cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    edges= cv2.Canny(gray, 10,255)
    contours, hierarchy= cv2.findContours(edges.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    sorted_contour = sorted(contours, key=cv2.contourArea, reverse= True)[0]
    
    x,y,w,h= cv2.boundingRect(sorted_contour)
    i=100
    cropped_contour= image[y:y+h, x:x+w]
    image_name= "output_shape_number_" + str(i) + ".jpg"
    cv2.imwrite(image_name, cropped_contour)
    readimage= cv2.imread(image_name)
    cv2.imshow('Image', readimage)
    cv2.waitKey(0)
        
    cv2.destroyAllWindows()
        

cropping_helper("lego_objects/1735.jpg", 256)

In [ ]:
def preprocess_image(image_path, target_size):
    image = skimage.io.imread(image_path)

    if image.shape[0] != image.shape[1]:
        diff = abs(image.shape[0] - image.shape[1])
        padding = [(0, 0), (0, 0), (0, 0)]
        if image.shape[0] > image.shape[1]:
            padding[1] = (diff // 2, diff - (diff // 2))
        else:
            padding[0] = (diff // 2, diff - (diff // 2))
        image = np.pad(image, padding, mode='constant', constant_values=255)

    image = skimage.transform.resize(image, (target_size, target_size))
    skimage.io.imshow(image)
    #return image

preprocess_image("lego_objects/5.jpg", 400)

In [ ]:
from PIL import Image as im
import numpy as np
def generate_image(input_img_path):

    image = np.load(input_img_path)
    

    output_image = image * 255
    output_image = output_image.astype(np.uint8)
    
    data = im.fromarray(output_image)
    if data.mode != 'RGB':
        data = data.convert('RGB')
      
    # saving the final output 
    # as a PNG file
    data.save('testing.png')

generate_image('/Users/carolinezhang/Downloads/lego-ization/lego_arrays/lego_113.npy')

In [9]:
from PIL import Image
import numpy as np

def crop_center(image):
    """
    Crop the image to 256x256 in the center.
    """
    width, height = image.size
    left = (width - 256) / 2
    top = (height - 256) / 2
    right = (width + 256) / 2
    bottom = (height + 256) / 2
    return image.crop((left, top, right, bottom))

# Load the image
image = Image.open("realworld_scenes/9104.jpg")

# Crop the image to 256x256 in the center
image = crop_center(image)
image = np.asarray(image)
print(image)
print(image.shape)

# Save the cropped image
#image.save("crop_test.jpg")

[[[193 208 205]
  [185 200 197]
  [178 194 191]
  ...
  [183 138 133]
  [180 137 130]
  [185 145 137]]

 [[192 208 205]
  [185 201 198]
  [179 195 192]
  ...
  [180 135 132]
  [182 139 133]
  [199 158 152]]

 [[193 209 206]
  [186 202 199]
  [180 196 193]
  ...
  [167 123 124]
  [178 137 133]
  [191 154 148]]

 ...

 [[ 99 103 114]
  [102 106 117]
  [105 109 120]
  ...
  [ 58  53  59]
  [ 55  50  56]
  [ 55  50  56]]

 [[103 107 118]
  [104 108 119]
  [106 110 121]
  ...
  [ 63  58  64]
  [ 52  47  53]
  [ 69  64  70]]

 [[103 107 118]
  [104 108 119]
  [105 109 120]
  ...
  [ 77  72  78]
  [ 62  57  63]
  [ 57  52  58]]]
(256, 256, 3)
