In [ ]:
import skimage
import numpy as np
from skimage import img_as_ubyte
import cv2

In [ ]:
import cv2
def cropping_helper(image_path, target_size):
    # Load the image and convert it to grayscale
    image = cv2.imread(image_path)
    gray= cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    edges= cv2.Canny(gray, 10,255)
    contours, hierarchy= cv2.findContours(edges.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    sorted_contour = sorted(contours, key=cv2.contourArea, reverse= True)[0]
    
    x,y,w,h= cv2.boundingRect(sorted_contour)
    i=100
    cropped_contour= image[y:y+h, x:x+w]
    image_name= "output_shape_number_" + str(i) + ".jpg"
    cv2.imwrite(image_name, cropped_contour)
    readimage= cv2.imread(image_name)
    cv2.imshow('Image', readimage)
    cv2.waitKey(0)
        
    cv2.destroyAllWindows()
        

cropping_helper("lego_objects/1735.jpg", 256)

In [ ]:
def preprocess_image(image_path, target_size):
    image = skimage.io.imread(image_path)

    if image.shape[0] != image.shape[1]:
        diff = abs(image.shape[0] - image.shape[1])
        padding = [(0, 0), (0, 0), (0, 0)]
        if image.shape[0] > image.shape[1]:
            padding[1] = (diff // 2, diff - (diff // 2))
        else:
            padding[0] = (diff // 2, diff - (diff // 2))
        image = np.pad(image, padding, mode='constant', constant_values=255)

    image = skimage.transform.resize(image, (target_size, target_size))
    skimage.io.imshow(image)
    #return image

preprocess_image("lego_objects/5.jpg", 400)

In [ ]:
from PIL import Image as im
import numpy as np
def generate_image(input_img_path):

    image = np.load(input_img_path)
    

    output_image = image * 255
    output_image = output_image.astype(np.uint8)
    
    data = im.fromarray(output_image)
    if data.mode != 'RGB':
        data = data.convert('RGB')
      
    # saving the final output 
    # as a PNG file
    data.save('testing.png')

generate_image('/Users/carolinezhang/Downloads/lego-ization/lego_arrays/lego_113.npy')

In [9]:
from PIL import Image
import numpy as np

def crop_center(image):
    """
    Crop the image to 256x256 in the center.
    """
    print(image.size)
    width, height = image.size
    left = (width - 256) / 2
    top = (height - 256) / 2
    right = (width + 256) / 2
    bottom = (height + 256) / 2
    image = image.crop((left, top, right, bottom))
    print(image)
    return image

# Load the image
image = Image.open("realworld_scenes/9110.jpg")

# Crop the image to 256x256 in the center
image = crop_center(image)
image = np.asarray(image)
print(image)
print(image.shape)

# Save the cropped image
#image.save("crop_test.jpg")

(800, 598)
<PIL.Image.Image image mode=L size=256x256 at 0x10F4D2620>
[[ 13   8  14 ...  40  41  44]
 [ 13  15  24 ...  29  35  44]
 [ 13  25  40 ...  31  33  36]
 ...
 [180 172 170 ...   2   0   1]
 [195 193 196 ...   2   1   0]
 [207 208 210 ...   1   2   0]]
(256, 256)
